### ISSUE TITLE
"Show examples" in Spanish translation

### ISSUE THREAD

**Issue by okusio** [Representable/representable#512] opened 2020-12-18 18:23 UTC
**Describe the bug**
When users click "mostrar ejemplos" in the survey page, it switches to English
 
**To Reproduce**
1. Go to survey page in spanish
2. Click on "mostrar ejemplos"

**Expected behavior**
Stays in Spanish

**Comment by k-y-le** [comment] 2020-12-23 07:13
closing, duplicate of #417

**Closed by k-y-le** 2020-12-23 07:13 UTC
